# Generated by Django 6.0.1 on 2026-02-04 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('todo', models.CharField(max_length=20)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
