# Generated by Django 6.0.1 on 2026-02-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
