# Generated by Django 6.0.1 on 2026-02-04 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todos_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
